networks:
  web:

volumes:
  static_volume:
  media_volume:
  postgres_data:

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [web]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks: [web]

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file: [.env]
    depends_on: [redis, postgres]
    networks: [web]
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}

  celery:
    build: ./backend
    restart: unless-stopped
    env_file: [.env]
    depends_on: [redis, postgres, backend]
    networks: [web]
    command: celery -A backend.celery_app worker -l info --concurrency=2
    volumes:
      - media_volume:/app/media
    environment:
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

  celery-beat:
    build: ./backend
    restart: unless-stopped
    env_file: [.env]
    depends_on: [redis, postgres, backend]
    networks: [web]
    command: celery -A backend.celery_app beat -l info
    environment:
      DEBUG: ${DEBUG}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: https://localhost:8000  # Change to actual API URL
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on: [backend]
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    networks: [web]
