# Generated by Django 5.1.4 on 2024-12-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('education', models.CharField(max_length=500)),
                ('courses', models.CharField(max_length=500)),
                ('certifications', models.CharField(max_length=500)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('teaching_style', models.CharField(max_length=200)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='toast_tutor.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.CharField(blank=True, default='Present', max_length=50)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_records', to='toast_tutor.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_list', to='toast_tutor.tutorprofile')),
            ],
        ),
    ]
