# Generated by Django 5.1.7 on 2025-06-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0002_meeting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={},
        ),
    ]
