# Generated by Django 5.1.7 on 2025-04-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0002_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
    ]
