# Generated by Django 5.1.4 on 2025-01-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0002_tutorprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='cover',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
