# Generated by Django 5.1.7 on 2025-05-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0003_alter_meeting_options'),
        # ('toast_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='status',
        ),
        migrations.AddField(
            model_name='meeting',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
