# Generated by Django 5.1.4 on 2025-01-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0003_tutorprofile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
