# Generated by Django 5.1.7 on 2025-05-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0004_remove_meeting_status_meeting_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
