# Generated by Django 5.1.4 on 2024-12-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0004_user_delete_student_alter_tutorprofile_tutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='education',
        ),
    ]
