# Generated by Django 5.1.4 on 2025-01-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0005_remove_course_grade_course_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teach_grade',
            new_name='grade',
        ),
    ]
