# Generated by Django 5.1.7 on 2025-05-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0006_meeting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='description',
        ),
    ]
