# Generated by Django 5.1.4 on 2025-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0006_resettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='resettoken',
            name='last_sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
