# Generated by Django 5.1.4 on 2025-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0006_rename_teach_grade_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=models.CharField(max_length=20),
        ),
    ]
