# Generated by Django 5.1.7 on 2025-06-04 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0007_remove_meeting_description_remove_meeting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending-Payment'), ('booked', 'Booked')], default='scheduled', max_length=10),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
