# Generated by Django 5.1.4 on 2025-01-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0007_alter_exam_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=10)),
                ('request_type', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=200)),
                ('min_pay', models.IntegerField()),
                ('max_pay', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('aim', models.CharField(max_length=40)),
                ('teaching_styles', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_requests', to='toast_tutor.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
