# Generated by Django 5.1.7 on 2025-05-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0008_meeting_organizer_email_meeting_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="organizer_email",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="student_email",
        ),
    ]
