# Generated by Django 5.1.4 on 2025-01-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0008_tutorrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='student',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='aim',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='max_pay',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='min_pay',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='teaching_styles',
        ),
    ]
