# Generated by Django 5.1.4 on 2025-01-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0009_rename_student_tutorrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
