# Generated by Django 5.1.4 on 2025-01-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0010_alter_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='teaching_style',
            field=models.JSONField(max_length=200),
        ),
    ]
