# Generated by Django 5.1.7 on 2025-05-28 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0011_remove_reviews_rating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
