# Generated by Django 5.1.7 on 2025-05-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0012_remove_review_profile_review_tutor_delete_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tutor',
            new_name='tutor_id',
        ),
    ]
