# Generated by Django 5.1.7 on 2025-05-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0013_rename_tutor_review_tutor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
