# Generated by Django 5.1.7 on 2025-05-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0015_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
