# Generated by Django 5.1.7 on 2025-05-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0017_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
