# Generated by Django 5.1.7 on 2025-06-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0003_alter_meeting_options'),
        ('toast_tutor', '0021_review_rating_delete_rating'),
    ]

    operations = [
    ]
