# Generated by Django 5.1.7 on 2025-06-10 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0022_merge_20250609_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("pending", "Pending-Payment"),
                    ("booked", "Booked"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booked_meetings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
