# Generated by Django 5.1.7 on 2025-06-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0023_alter_meeting_status_alter_meeting_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("Offline", "Offline"), ("Online", "Online")],
                default="Offline",
                help_text="User account status",
                max_length=20,
            ),
        ),
    ]
