# Generated by Django 5.1.7 on 2025-06-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0023_alter_meeting_status_alter_meeting_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="Offline", max_length=10),
        ),
    ]
