# Generated by Django 5.2.3 on 2025-06-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0024_chatbox_message_chatbox_unique_user1_user2_pair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
