# Generated by Django 5.1.7 on 2025-06-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0025_remove_user_status_tutorprofile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorprofile",
            name="status",
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="Offline", max_length=20),
        ),
    ]
