# Generated by Django 5.2.3 on 2025-06-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast_tutor', '0025_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
