# Generated by Django 5.1.7 on 2025-06-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0026_remove_tutorprofile_status_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.AddField(
            model_name="tutorprofile",
            name="status",
            field=models.CharField(default="Offline", max_length=20),
        ),
    ]
