# Generated by Django 5.1.7 on 2025-06-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0028_remove_tutorprofile_status_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
    ]
