# Generated by Django 5.1.7 on 2025-06-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0029_remove_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="active", max_length=50),
        ),
    ]
