# Generated by Django 5.1.7 on 2025-06-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toast_tutor", "0031_remove_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
